apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aws-sample
  template:
    metadata:
      labels:
        app: aws-sample
    spec:
      containers:
        - name: aws-sample
          image: 682033465707.dkr.ecr.eu-north-1.amazonaws.com/aws-sample:latest
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: connectionString