apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: 682033465707.dkr.ecr.eu-north-1.amazonaws.com/aws-sample:latest
          command: ["dotnet", "AWS.Sample.API.dll", "migrate"]
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: connectionString