apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  connectionString: SG9zdD1wb3N0Z3JlcztQb3J0PTU0MzI7RGF0YWJhc2U9YXdzX3NhbXBsZV9kYjtVc2VybmFtZT1hd3Nfc2FtcGxlX3VzZXI7UGFzc3dvcmQ9YXdzX3NhbXBsZV9wYXNzd29yZA==