name: Deploy to AWS EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: aws-sample
          IMAGE_TAG: latest
        run: |
          docker build --platform=linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f devops/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region eu-north-1 --name EKS-eberinda-test-Claster

      - name: Apply Migration Job
        run: |
          kubectl apply -f infra/migration-job.yaml
          kubectl wait --for=condition=complete --timeout=300s job/migration-job || kubectl logs job/migration-job
          kubectl delete job migration-job || true

      - name: Check Environment Variables in Pod
        run: |
          kubectl exec deployment/aws-sample -- printenv | grep ConnectionStrings__DefaultConnection

      - name: Wait for Migration Job to Complete
        run: |
          kubectl wait --for=condition=complete --timeout=300s pod/migration-job || kubectl logs migration-job

      - name: Cleanup Migration Job
        run: |
          kubectl delete pod migration-job || true

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/aws-sample aws-sample=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          kubectl rollout restart deployment aws-sample

      - name: Get Application Logs
        run: |
          kubectl logs deployment/aws-sample --tail=50